version: "3.9"

services:
  web:
    build: .
    #command: python /app_backend/manage.py runserver 0.0.0.0:
    command: gunicorn backend.wsgi -b 0.0.0.0:8000 # new
    volumes:
      - .:/app_backend
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
     - "DJANGO_SECRET_KEY=django-insecure-7))1x36$$sxgfmz=cq-(0$$(pqcdl--)vyy=ff&%*1zmp2xvq&-1"
     - "DJANGO_DEBUG=True"
     - "DJANGO_SECURE_SSL_REDIRECT=False" # new
     - "DJANGO_SECURE_HSTS_SECONDS=0" # new
     - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" # new
     - "DJANGO_SECURE_HSTS_PRELOAD=False" # 
     - "DJANGO_SESSION_COOKIE_SECURE=False" # new
     - "DJANGO_CSRF_COOKIE_SECURE=False" # new
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: